Add staging variables for payments admin deployment
companieshouse/payments-service-stack pull request #28
Opened 2022-04-13 13:29 UTC by jphillips2121

2022-04-14 07:11 UTC, macreman requested changes

2022-04-14 07:11 UTC, macreman commented on groups/stack/profiles/development-eu-west-2/staging/vars
> +internal_top_level_domain = "-internal-api-staging-aws.companieshouse.gov.uk"
I think this one should be 

`internal_top_level_domain = ".staging.aws.internal"`

2022-04-14 07:11 UTC, macreman commented on groups/stack/profiles/development-eu-west-2/staging/vars
> +cookie_domain = "companieshouse.gov.uk"
`cookie_domain = "company-information.service.gov.uk"`

2022-04-14 07:11 UTC, macreman commented on groups/stack/profiles/development-eu-west-2/staging/vars
> +internal_api_url = "https://internal-api-staging-aws.companieshouse.gov.uk"
pretty sure this and all of the configs below that end with `companieshouse.gov.uk` should end with `company-information.service.gov.uk` instead

2022-04-14 07:11 UTC, macreman commented on groups/stack/profiles/development-eu-west-2/staging/vars
> +pay_web_cdn_host = "d309scb72axzzb.cloudfront.net"
current cdn host in staging mesos golbal_env is 
`export CDN_HOST=d3s4qnqz7t874x.cloudfront.net # cdn.ch.gov.uk-3.22.170`
so unless theres a specific reason to have a different one (maybe this one is newer and not in global_env yet?) we should probably match this

2022-04-19 08:43 UTC, emead approved these changes

2022-04-19 08:45 UTC, merged